
#include <stdint.h>

#ifndef BMC_MAX_KEY_LENGTH
# define BMC_MAX_KEY_LENGTH  250
#endif
#ifndef BMC_CACHE_ENTRY_COUNT
# define BMC_CACHE_ENTRY_COUNT  3250
#endif
#ifndef FNV_OFFSET_BASIS_32
# define FNV_OFFSET_BASIS_32  2166136261u
#endif
#ifndef FNV_PRIME_32
# define FNV_PRIME_32  16777619u
#endif

#include <klee/klee.h>

/*
 * AI-derived function summary for bmc_hash_keys().
 * Auto-generated by lifting_tools/summarizer/summarize.py
 *
 * Stage 2 (side effects):  Clam zones-domain invariants at loop exit.
 * Stage 3 (return bound):  known-bits ⊗ interval domain
 *   mod_type=urem  mod_val=3250  → result ∈ [0, 3249]
 */
uint32_t bmc_hash_keys(const char *payload, unsigned int len, unsigned int *out_key_len)
{
    (void)payload;
    (void)len;

    /* [Stage 2] side effect: *out_key_len */
    unsigned int out_key_len_se;
    klee_make_symbolic(&out_key_len_se, sizeof out_key_len_se, "out_key_len");
    klee_assume(out_key_len_se <= 251);
    *out_key_len = out_key_len_se;

    /* [Stage 3] return value bound: urem mod_val=3250 → max=3249 */
    uint32_t result;
    klee_make_symbolic(&result, sizeof result, "result");
    klee_assume(result < BMC_CACHE_ENTRY_COUNT);
    return result;
}
