#include <stdint.h>

#ifndef LOOP_BOUND
# define LOOP_BOUND 32
#endif

#define FNV_OFFSET_BASIS_32 2166136261u
#define FNV_PRIME_32        16777619u

#include <klee/klee.h>

/*
 * AI-derived function summary for perbyte_hash().
 * Auto-generated by lifting_tools/summarizer/summarize.py
 *
 * Stage 2 (side effects):  Clam zones-domain invariants at loop exit.
 * Stage 3 (return bound):  known-bits ⊗ interval domain
 *   mod_type=urem  mod_val=1000  → result ∈ [0, 999]
 */
uint32_t perbyte_hash(const char *payload, unsigned int len, unsigned int *out_matches)
{
    (void)payload;
    (void)len;

    /* [Stage 2] side effect: *out_matches */
    unsigned int out_matches_se;
    klee_make_symbolic(&out_matches_se, sizeof out_matches_se, "out_matches");
    klee_assume(out_matches_se <= 32);
    *out_matches = out_matches_se;

    /* [Stage 3] return value bound: urem mod_val=1000 → max=999 */
    uint32_t result;
    klee_make_symbolic(&result, sizeof result, "result");
    klee_assume(result < 1000);
    return result;
}
