#include <stdint.h>

typedef uint16_t __u16;
typedef uint64_t __u64;

#include <klee/klee.h>

/*
 * AI-derived function summary for csum_fold_helper().
 * Auto-generated by lifting_tools/summarizer/summarize.py
 *
 * Stage 2 (side effects):  Clam zones-domain invariants at loop exit.
 * Stage 3 (return bound):  known-bits ⊗ interval domain
 *   mod_type=and_mask  mod_val=65535  → result ∈ [0, 65535]
 */
__u16 csum_fold_helper(__u64 csum)
{
    (void)csum;

    /* [Stage 3] return value bound: and_mask mod_val=65535 → max=65535 */
    __u16 result;
    klee_make_symbolic(&result, sizeof result, "result");
    klee_assume(result <= 65535);
    return result;
}
