#include <klee/klee.h>

/*
 * AI-derived function summary for get_packet_hash().
 * Auto-generated by lifting_tools/summarizer/summarize.py
 *
 * Stage 2 (side effects):  Clam zones-domain invariants at loop exit.
 * Stage 3 (return bound):  known-bits ⊗ interval domain
 *   mod_type=urem  mod_val=127  → result ∈ [0, 126]
 */
u32 get_packet_hash(const unsigned char srcv6[16], u32 ports)
{
    (void)srcv6[16];
    (void)ports;

    /* [Stage 3] return value bound: urem mod_val=127 → max=126 */
    u32 result;
    klee_make_symbolic(&result, sizeof result, "result");
    klee_assume(result < 127);
    return result;
}
