#include <stdint.h>

#define PREPARE_TYPE_LEN    33
#define REQUEST_TYPE_LEN    33
#define PREPAREOK_TYPE_LEN  35
#define MYPREPAREOK_TYPE_LEN 24

#define FAST_PROG_XDP_HANDLE_PREPARE   0
#define FAST_PROG_XDP_HANDLE_REQUEST   1
#define FAST_PROG_XDP_HANDLE_PREPAREOK 2

#include <klee/klee.h>

/*
 * AI-derived function summary for compute_message_type().
 * Auto-generated by lifting_tools/summarizer/summarize.py
 *
 * Stage 2 (side effects):  Clam zones-domain invariants at loop exit.
 * Stage 3 (return bound):  known-bits ⊗ interval domain
 *   mod_type=unbounded  mod_val=0  → result ∈ [0, 4294967295]
 */
int compute_message_type(char *payload, void *data_end)
{
    (void)payload;
    (void)data_end;

    /* [Stage 3] return value bound: unbounded mod_val=0 → max=4294967295 */
    int result;
    klee_make_symbolic(&result, sizeof result, "result");
    return result;
}
