#include <stdint.h>
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include "bpf_map_def.h"

#ifndef CHAIN
#define CHAIN 128
#endif
#define TBL_SIZE 256

#include <klee/klee.h>

/*
 * AI-derived function summary for do_gather().
 * Auto-generated by lifting_tools/summarizer/summarize.py
 *
 * Stage 2 (side effects):  Clam zones-domain invariants at loop exit.
 * Stage 3 (return bound):  known-bits ⊗ interval domain
 *   mod_type=and_mask  mod_val=255  → result ∈ [0, 255]
 */
uint32_t do_gather(struct bpf_map_def *tbl, unsigned int start_idx)
{
    (void)tbl;
    (void)start_idx;

    /* [Stage 3] return value bound: and_mask mod_val=255 → max=255 */
    uint32_t result;
    klee_make_symbolic(&result, sizeof result, "result");
    klee_assume(result <= 255);
    return result;
}
